config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :trainings  do
    resources :likes, only: [:create, :destroy]
  end
  # get    'muscles'          => 'muscles#index'
  # musclesという文字をURLで入力するとmusclesコントローラーindexというアクションに行く
  get 'users' =>'users#index' 
  root 'trainings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :training
  belongs_to :user
  validates_uniqueness_of :training_id, scope: :user_id
end

app/models/training.rb
class Training < ApplicationRecord
    belongs_to :user 
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :trainings, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :liked_trainings, through: :likes, source: :training
         def already_liked?(training)
          self.likes.exists?(training_id: training.id)
        end
        has_many :trainings, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
        validates :name, presence: true #追記
        validates :profile, length: { maximum: 200 } #追記
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      # deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(training_id: params[:training_id]) #user_idとtweet_idの二つを代入
        if like.save!
            redirect_back(fallback_location: root_path)
        end
      end
    
      def destroy
        like = Like.find_by(training_id: params[:training_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :authenticate_user!

    def index
        @trainings = Training.all
    end
    def new
        @trainings=Training.new 
      end

      def create
        trainings = Training.new(trainings_params)
        trainings.user_id = current_user.id 
        url = params[:youtube_url]
        if url.present?
          trainings.youtube_url = url
        end
        if trainings.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @trainings = Training.find(params[:id])
      end

      def edit
        @trainings = Training.find(params[:id])
      end

      def update
        trainings = Training.find(params[:id])
        if trainings.update(trainings_params)
          redirect_to :action => "show", :id => trainings.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        trainings = Training.find(params[:id])
        trainings.destroy
        redirect_to action: :index
      end

      

      private
      def trainings_params
        params.require(:training).permit(:title, :show, :youtube_url, :user_id, :category)
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
     

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/muscles_helper.rb
module MusclesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's workout</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/069b37131a.js" crossorigin="anonymous"></script>
    <link rel="styleheet" href="https//unpkg.com/ress/dist/ress.min.css">
    <link rel="stylesheet" href="application.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rampart+One&family=Young+Serif&display=swap" rel="stylesheet">
  </head>

  <body>
  <header>
      <h1>Let's workout</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "ホーム", trainings_path %></li>
        <% unless user_signed_in? %>
        <li><%= link_to "ログイン", new_user_session_path %></li>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to "マイページへ", user_path(current_user.id) %></li>
          <li><%= button_to "ログアウト", destroy_user_session_path,class:'logout' ,method: :delete %></li>
        <% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to "秘密のページへ",  new_training_path %></li>
  <% end %>
<% end %>
 

      </ul>
      </div>
    </header>
    <main>
    <%= yield %>
  </main>
  <footer>
  <p>Copyright © Let's workout All Rights Reserved.</p>
</footer>
  </body>
</html>

app/views/trainings/edit.html.erb
<%= form_for @trainings do |f| %>
    <%= f.label :body %>
    <%= f.text_field :title, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/trainings/index.html.erb
<link rel="stylesheet" href="index.css">
<div class="top-image">
<h1>気軽に筋トレしよう！</h1>
<h3>Trainings一覧</h3> 
<div class="font-size">
 筋トレ初心者
</div>
<div class="card-parent">
  <% @trainings.each do |t| %>
    <% if t.category == "beginner" %>
      <div class="trainings">
        <div class="child-element">
          <div class="image-parent"><iframe width="100%" height="100%" src="https://www.youtube.com/embed/<%=t.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
          <h3><%= t.title %></h3>
          <div class="f-container">
            <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                <%= button_to training_like_path(id: t.id, training_id: t.id), method: :delete do %>
                  <i class="fas fa-heart"></i> <%= t.likes.count %>
                <% end %>
              <% else %>
                <%= button_to training_likes_path(id: t.id, training_id: t.id), method: :post do %>
                  <i class="far fa-heart"></i> <%= t.likes.count %>
                <% end %>
              <% end %>
            <% else %>
            <i class="far fa-heart"></i> <%= t.likes.count %>
            <% end %>
              <%= link_to "詳細へ", training_path(t.id) %> 
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div> 
<div class="font-size">
 本気で痩せたい人向け
</div>
<div class="card-parent">
  <% @trainings.each do |t| %>
    <% if t.category == "slimming" %>
      <div class="trainings">
        <div class="child-element">
          <div class="image-parent"><iframe width="100%" height="100%" src="https://www.youtube.com/embed/<%=t.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
          <%= t.title %>
          <div class="f-container">
            <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                <%= button_to training_like_path(id: t.id, training_id: t.id), method: :delete do %>
                  <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
              <% else %>
                <%= button_to training_likes_path(id: t.id, training_id: t.id), method: :post do %>
                  <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
              <% end %>
            <% else %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
            <%= link_to "詳細へ", training_path(t.id) %> 
          </div>
        </div>
      </div>
    <% end %>
  <% end %> 
</div>
<div class="font-size">
 筋トレ・ダイエットのための食事
</div>
<div class="card-parent">
  <% @trainings.each do |t| %>
    <% if t.category == "meal" %>
      <div class="trainings">
        <div class="child-element">
          <div class="image-parent"><iframe width="100%" height="100%" src="https://www.youtube.com/embed/<%=t.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
          <%= t.title %>
          <div class="f-container">
            <% if user_signed_in? %>
              <% if current_user.already_liked?(t) %>
                <%= button_to training_like_path(id: t.id, training_id: t.id), method: :delete do %>
                  <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
              <% else %>
                <%= button_to training_likes_path(id: t.id, training_id: t.id), method: :post do %>
                  <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
              <% end %>
            <% else %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
            <%= link_to "詳細へ", training_path(t.id) %> 
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
</div>

app/views/trainings/new.html.erb
<h1>Let's workout</h1>
<h3>Muscles一覧</h3>
<%= form_for @trainings do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :size => 140 %>
  </div>
  <%= f.select :category, [["筋トレ初心者", "beginner"], ["本気で痩せたい人向け", "slimming"], ["筋トレ・ダイエットのための食事", "meal"]], include_blank: "どの投稿？" %>

  <div class="field">
    <%= f.label :youtube_url %>
    <%= f.text_field :youtube_url, :size => 140 %>
  </div>
  <%= f.submit "投稿する" %>
<% end %>
<%= link_to "Muscle一覧に戻る", trainings_path %>



app/views/trainings/show.html.erb
<h1>Let's workout</h1>
<h3>Trainings詳細</h3>
<div class="trainings">
  <p><%= @trainings.title %></p>
  <p><%= @trainings.created_at %></p>
  <% if user_signed_in? %>
  <% if current_user.already_liked?(@trainings) %>
    <%= button_to training_like_path(@trainings), method: :delete do %>
      <p>いいねを取り消す</p><%= @trainings.likes.count %>
      <i class="fa-solid fa-heart"></i><%= @trainings.likes.count %>
    <% end %>
  <% else %>
    <%= button_to training_like_path(@trainings), method: :post do %>
      <i class="fa-solid fa-heart"></i><%= @trainings.likes.count %>
      <p>いいね</p><%= @trainings.likes.count %>
    <% end %>
  <% end %>
<% else %>
  <p>いいねの数 = </p><%= @trainings.likes.count %>
  <i class="fa-solid fa-heart"></i><%= @trainings.likes.count %>
<% end %>
<%= link_to "編集する", edit_training_path(@trainings.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @trainings.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= link_to "Muscle一覧に戻る", trainings_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

 
<h2>ユーザーの投稿一覧</h2>
<% @user.trainings.each do |t| %>
  <%= t.user.name %>
  <%= t.title %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_trainings.each do |t| %>
  <%= t.user.name %>
  <%= t.title %>
<% end %>
<!-- ここまで-->

<%= link_to "Trainings一覧に戻る", trainings_path %>